### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by hiulit** [hiulit/Godot-2D-Platformer-Test#1]
- [ ] Lever mechanics
- [ ] Wind
- [ ] Water
- [ ] Rain
- [ ] Popup showing item collected
- [ ] HUD (Lives, score, points, etc)
- [ ] Minimap
- [ ] Puzzles
- [ ] Tutorial "on the go" (show what to do at the right moment)
- [ ] Ladders
- [ ] Grab to wall
- [ ] Level transitions
- [ ] Ropes
